### ISSUE TITLE
Is it possible serialize the final steps of common factor GWAS?

### ISSUE THREAD

**Issue by drveera** [MichelNivard/GenomicSEM#13]
Hi Michel and Elliott,

 I've been working on your tutorials for past few days. I've many comments, which I'll write them all together in few days. The tutorials are helpful and it's been written with care, with end user in mind. I appreciate that. For now I've two quick questions. 
1. Is it possible to run step 4 (Combine the summary statistics and LDSC output) and step 5(Run the multivariate GWAS) in batches? For example, Can I run chromosome wise, or in batches of 10000 SNPs ? Do the functions `addSNPs` and `commonfactorGWAS` require the whole info from all SNPs?

2. I'm trying your tutorials for commonfactor GWAS for five psychiatric disorders. Can you provide me the summary statistics that you've generated for this case, so that I can compare it with mine?

Thanks 

Regards
Veera

**Comment by agrotzin** [comment]
Hi Veera, 

Glad you are using the package! For your first question each run is entirely independent of one another so it is completely fun to batch things. In fact, if you have access to a computing cluster that allows you to submit multiple jobs I'd recommend it. For your second question, I'll get those summary stats up in the next few days and will post here with the link to the file and readME. If you could also post in the google group (link below) for any future questions we are trying to make that a consolidated place for any user questions/issues.  

https://groups.google.com/forum/#!forum/genomic-sem-users

Best, 
-Andrew

**Comment by drveera** [comment]
Hi Andrew,

Thanks for the reply. I was not aware of the google group. I'll post there hereafter. Great that you'll share the sumstats in few days. Looking forward to it. 

Regards
Veera

**Comment by agrotzin** [comment]
Hi Veera, 

Just a note that the sumstats are up on the box folder along with a readME file. Let me know if you have any other questions! https://utexas.box.com/s/vkd36n197m8klbaio3yzoxsee6sxo11v

Andrew

**Comment by drveera** [comment]
Hi Andrew,

Just realised I haven't got back to you on this. I downloaded the summary statistics and it matches with the one I produced following your tutorials. It was very helpful. thank you very much. 

Regards
Veera

**Comment by agrotzin** [comment]
Hi Veera, 

Great, thanks for confirming and glad you got results that match! 

Best, 
  Andrew
