### ISSUE TITLE
link to reference zip file

### ISSUE THREAD

**Issue by scimerc** [MichelNivard/GenomicSEM#16]
the reference file that can be found at [this link](https://utexas.box.com/s/vkd36n197m8klbaio3yzoxsee6sxo11v) in the wiki section on `sumstats` is a zip file, which `data.table::fread` does not seem to handle well. it would be helpful to mention that it should be unzipped before use. or replace it with a gzip archive for example.

**Comment by MichelNivard** [comment]
Okay, will see about changing that, thanks for the suggestion.

**Comment by agrotzin** [comment]
Hi! That's a great point. I've updated the files to be a gzip archive. Let us know if you have any more issues.
