### ISSUE TITLE
Regarding the update 

### ISSUE THREAD

**Issue by drveera** [MichelNivard/GenomicSEM#17]
Hi ,

It's great that you guys have found a bug, and also updated the package. But just to let you know that it broke my pipeline, when I updated the R package, and I had to dig around to fix it. A request for any future updates, please make sure that the old functions still work with the update. And in the tutorial for userGWAS, in the step 4, the code reads as below.

```
#specify the model
model<-"F1 =~ mood + misery + irritability + fedup + lonely + guilt
F2 =~ hurt + nervous + worry + tense + embarass + nerves
F1~~F2
F1 ~ SNP
F2 ~ SNP"

#run the multivariate GWAS using parallel processing
CorrelatedFactors<-userGWAS(covstruc = LDSCoutput, sumstats = neuroticism_sumstats, estimation = "DWLS", model = model, modelchi = TRUE, printwarn = TRUE, sub=c("F1~SNP", "F2~SNP"), cores = NULL, toler = FALSE, SNPSE = FALSE, parallel = TRUE, Output = NULL)
```
The second argument in the CorrelatedFactors is `SNPs`, and not `sumstats`. Again, I am guessing  (I don't remember) this is because you changed the argument name from `sumstats` to `SNPs`.  It might not be a good idea to change the argument names in a minor update.

Anyways, it's a great package, as I've mentioned before. Thank you for keeping it active. 

Regards
Veera

**Comment by MichelNivard** [comment]
Hi Veera,

we suspected this could happen.  We had a try and strike a balance between speeding up every one's analysis and risk of breaking existing code. So strictly speaking the old arguments (if you call the explicitly e.g. as <- rnorm(n=100,mean=0,sd=10)) should still work, but if you passed arguments by order to the function (e.g. a <- rnorm(100,0,10)) things indeed go wrong. 

We''l look into the example in the tutorial ASAP.

Again sorry for the issues, we hope you will appreciate the speedier analyses though ;)

Best,
Michel

**Comment by drveera** [comment]
You guessed it right. My pipeline broke because the order of the arguments changed. It's of course my mistake to pass parameters without argument names. I haven't checked if the update made the functions faster. But if it is so, then great!!
Thanks for quick response. 

Regards
Veera
