### ISSUE TITLE
munge function description in wiki and R-man

### ISSUE THREAD

**Issue by scimerc** [MichelNivard/GenomicSEM#18]
it isn't clear whether the `hm3` argument of the `munge` function is *supposed* to be a HapMap SNP list or just *could/should* be a HapMap SNP list. R's `munge` online help would seem to indicate the former, the wiki more the latter.

**Comment by agrotzin** [comment]
Good point; I've updated the munge man as it is the latter of could/should be a HapMap SNP list.
