### ISSUE TITLE
LD scores directory

### ISSUE THREAD

**Issue by scimerc** [MichelNivard/GenomicSEM#19]
this [wiki article](https://github.com/MichelNivard/GenomicSEM/wiki/3.-Models-without-Individual-SNP-effects#step-2-run-multivariable-ldsc) basically says that these directories "should be in a subdirectory of the" working directory, but judging by the code, I assume what's meant with this is, as usual, that relative paths are assumed unless an absolute one is specified. I would write it this way or just omit it.

**Comment by agrotzin** [comment]
This text has been updated.
