### ISSUE TITLE
commonfactorGWAS - system is computationally singular

### ISSUE THREAD

**Issue by AndreAllegrini** [MichelNivard/GenomicSEM#2]
Hi,
I'm running the common factor GWAS with summary statistics from a pair of continuous traits (highly correlated), and I get this error:

> factor <- commonfactorGWAS(SNPcov, estimation = "DWLS")
Error in solve.default(t(S2.delt) %*% S2.W %*% S2.delt) :
  system is computationally singular: reciprocal condition number = 2.37236e-18
Calls: commonfactorGWAS -> solve -> solve -> solve.default
In addition: Warning messages:
1: In lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats,  :
  lavaan WARNING: could not compute standard errors!
  lavaan NOTE: this may be a symptom that the model is not identified.
 2: In lav_object_post_check(object) :
  lavaan WARNING: some estimated ov variances are negative
Execution halted
 
This happens also with a different set of summary stats (moderate correlations):

> factor <- commonfactorGWAS(SNPcov, estimation = "DWLS")
Error in solve.default(t(S2.delt) %*% S2.W %*% S2.delt) :
  system is computationally singular: reciprocal condition number = 1.14347e-16
Calls: commonfactorGWAS -> solve -> solve -> solve.default
In addition: Warning message:
In lav_object_post_check(object) :
  lavaan WARNING: some estimated lv variances are negative
Execution halted

Best,
Andrea

**Comment by AndreAllegrini** [comment]
Hi Michel,

1. the common factor model without a SNP didn't work.

2. These are the matrices output by ldsc: 

> LDSCout
$V
             [,1]         [,2]         [,3]
[1,] 4.735547e-05 2.181039e-05 1.233898e-05
[2,] 2.181039e-05 1.539171e-05 8.451578e-06
[3,] 1.233898e-05 8.451578e-06 1.089871e-05

$S
          [,1]      [,2]
[1,] 0.1933609 0.1110442
[2,] 0.1110442 0.1228192

$I
          [,1]      [,2]
[1,] 1.0411620 0.1430688
[2,] 0.1430688 0.9778608

Thanks

**Comment by MichelNivard** [comment]
And the S V and I 3 indicator problem? (there are different issues at play). The issue with 2 indicators is systemic, the factor model needs special constraints to be identified if you have 2 indicators, currently your estimating more parameters than you have degrees of freedom. The issue with the 3 indicator model could be easily solvable though.

**Comment by AndreAllegrini** [comment]
Great, thanks! I will try now with the new SNPSE value. 

Here are the V, S, I matrices for the 3 indicator model: 

> LDSCout
$V
             [,1]          [,2]          [,3]          [,4]          [,5]
[1,] 1.037804e-05  2.421884e-06  2.377333e-06  2.601582e-06  3.797867e-07
[2,] 2.421884e-06  1.056180e-05 -2.100318e-07  3.260665e-06  2.600882e-06
[3,] 2.377333e-06 -2.100318e-07  1.112221e-05  2.024669e-06  1.690500e-06
[4,] 2.601582e-06  3.260665e-06  2.024669e-06  4.444720e-05  4.136257e-06
[5,] 3.797867e-07  2.600882e-06  1.690500e-06  4.136257e-06  2.422683e-05
[6,] 2.438040e-06 -2.859007e-06  6.175943e-06 -5.251897e-06 -1.635080e-06
              [,6]
[1,]  2.438040e-06
[2,] -2.859007e-06
[3,]  6.175943e-06
[4,] -5.251897e-06
[5,] -1.635080e-06
[6,]  5.307321e-05
$S
           [,1]         [,2]         [,3]
[1,] 0.06907821  0.024552898  0.031037027
[2,] 0.02455290  0.085660140 -0.003756162
[3,] 0.03103703 -0.003756162  0.120338717
$I
           [,1]         [,2]         [,3]
[1,] 0.99931468  0.035356735  0.060273227
[2,] 0.03535674  1.005660240 -0.004911361
[3,] 0.06027323 -0.004911361  0.995417227

**Comment by MichelNivard** [comment]
For the 3 indicator model you may be faced with  model misfit, that is a single common factor isn't likely to explain the variance between these 3 traits.  Note that some of the co-variances in S are negative (between trait 2 and 3), is this what you expect based on the nature of the trait?

Best,
Michel

**Comment by AndreAllegrini** [comment]
Thanks, that makes sense. Yes, in hindsight the weak/null relationship between those two traits is to be expected.

**Comment by MichelNivard** [comment]
Alright Andrea, I consider the issue closed for now, email me or open another issue if you run into trouble with these traits or another GenomicSEM model!
