### ISSUE TITLE
Exit error when using ML estimator in usermodel()

### ISSUE THREAD

**Issue by jluningham** [MichelNivard/GenomicSEM#22]
When running `usermodel()` with `estimation="ML"`, the process fails due to the following error: 
`Error in cbind(unstand2, stand2) : object 'unstand2' not found`

It appears that `unstand2` and `stand2` are never defined within the ML estimation procedure. 

Further, I changed `unstand2` to `unstand` and the subsequent code fails because `base_model` and `results` no longer align (lines 1441-1448).

**Comment by agrotzin** [comment]
Sorry about that Justin and thanks for bringing this up. Just put in the patch for the ML estimation and it should be good to go.
