### ISSUE TITLE
commonfactorGWAS forking: rbind issue?

### ISSUE THREAD

**Issue by EmmaS85** [MichelNivard/GenomicSEM#23]
Hi Michel Nivard,

We are trying to run commonfactorGWAS in parallel mode. It doesn't give us any output, just an rbind error. It works fine in serial mode (I checked for 200 SNPs only).

Some experimentation with the script implies (to me) that it is computing everything ok for every SNP, on multiple cores indeed. However, after >12hours of processing it seems to be unable to save the output, i.e. to rbind the output for each SNP together. I am not familiar with parallel processing within R, so I have no clue how to fix this, or come up with a workaround. So I hope you may have an idea. 

We are using a Torque cluster and R 3.5.1. We are using DWLS estimation, and the latest version of genomicSEM.

Best wishes,

Emma

########### extra info: final output / Error ###############
N.B. I edited the script slightly to print SNP i and core n as it went along to check the process
........
[1] "------ core:  15 total SNPs:  135108  SNP:  135077"
[1] 135077
[1] "------ core:  15 total SNPs:  135108  SNP:  135092"
[1] 135092
[1] "------ core:  15 total SNPs:  135108  SNP:  135107"
[1] 135107
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

**Comment by agrotzin** [comment]
Hi Emma, 

Could you e-mail the LDSC output, the sumstats output, and the code you ran to agrotzin@utexas.edu? 

Thanks!
 -Andrew

**Comment by EmmaS85** [comment]
Thank you, Andrew, for your help with this! 

It took a while to conduct more tests bc I had to wait 48-72 hours every time. In these latter tests it always crashed only after running out of walltime. But with 10-20 processors requested that shouldn't be the cause, just the effect of the problem. Also with 256G working memory, I doubt that was the problem, though it is possible that our cluster configuration somehow did not allocate the right amount at all times...

Anyway, my colleague got it to work on our other cluster yesterday. So we are going to proceed there as well now. We conclude it is a system-specific issue that is not my job to resolve (let alone yours!). 

Thanks again and I'll let you know what we find out science-wise!
