### ISSUE TITLE
convert hold_names in munge.R

### ISSUE THREAD

**Issue by Xuemin-Wang** [MichelNivard/GenomicSEM#25]
Dear author,

The current munge.R script will throw an error if the columns are not named in the ones mentioned in the code, for example if the effect column was named as "z". It can be more robust by converting all columns names to upper or lower cases, such as by using the below in stead in line 28:
hold_names <- toupper(names(files[[i]])

If you decide to do so, obviously codes in line 32, 37, 42, 47, and 52 need to be updated as well.

Regards,

**Comment by agrotzin** [comment]
Great point! Will add this in this weekend and close the issue when done.

**Comment by agrotzin** [comment]
Both the sumstats and munge function have been edited to add this line of code and use only all upper case fields to search for matching column names. Thanks again for the suggestion!
