### ISSUE TITLE
Running mmDS

### ISSUE THREAD

**Issue by yuyingxie** [MichelNivard/GenomicSEM#27]
I tried to run the mmDS using negative binomial model and had the following error message.

Do you know how to fixt it?

> res <- mmDS(sce, method = "nbinom", n_threads = 2, verbose = FALSE)
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
In addition: Warning message:
In MulticoreParam(n_threads, progressbar = verbose) :
  MulticoreParam() not supported on Windows, use SnowParam()
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) :

**Comment by MichelNivard** [comment]
Hi, this isn't a function of GenomicSEM, I havent ever heard of the function. Cna you elaborate on why you ask this Q here?

**Comment by yuyingxie** [comment]
Sorry. It was a mistake.
