### ISSUE TITLE
'gzcat' in s_ldsc

### ISSUE THREAD

**Issue by floryhyy** [MichelNivard/GenomicSEM#30]
the function s_ldsc use command line 'gzcat' to reading gz files, which is not supported by windows system, Can you modify the code slightly so it will not require to execute the command 'gzcat' on console? I think R has many ways to reading gz file directly.

Below is the error message I got:
"The following annotations were added to the model: "
[1] "../1000G_Phase3_baselineLD_v2.2_ldscores/,"
[1] "\nReading in LD scores from ../1000G_Phase3_baselineLD_v2.2_ldscores/.[1-22]\n"
'gzcat' is not recognized as an internal or external command,
operable program or batch file.
'gzcat' is not recognized as an internal or external command,
operable program or batch file.
'gzcat' is not recognized as an internal or external command,
operable program or batch file.
'gzcat' is not recognized as an internal or external command,
operable program or batch file.
'gzcat' is not recognized as an internal or external command,
'gzcat' is not recognized as an internal or external command,
operable program or batch file.
[1] "ERROR:number of annotations does not match between LD scores and .M_5_50 files"
Error in s_ldsc(traits = munged.traits, sample.prev = sample.prev, population.prev = population.prev,  : 
  
In addition: There were 46 warnings (use warnings() to see them)

**Comment by agrotzin** [comment]
Thanks very much for raising this issue and apologies for the late reply! I've updated the s_ldsc code so it should be windows compatible, but of course let me know if you are still running into issues.
