### ISSUE TITLE
Regarding the speed of the programe

### ISSUE THREAD

**Issue by HongyanR** [MichelNivard/GenomicSEM#31]
Hi, I have been using GenomicSEM to run commonfactorGWAS on 4 phenotypes with 1000000+SNPs, and found it took quite a long time (the programme  has been running for 2 days and there is no sign of finishing). Is it normal?
My computer specs include: Mac OS, 4G ram, and 256 g ssd.

**Comment by agrotzin** [comment]
That isn't necessarily unusual, and in general running the GWAS functions is best done on a computing cluster if that is something you have access too. Take a look at this thread on the Genomic SEM google group for some suggestions: 
https://groups.google.com/u/1/g/genomic-sem-users/c/ZJtXg56fQsg
