### ISSUE TITLE
non-numeric argument to binary operator

### ISSUE THREAD

**Issue by HongyanR** [MichelNivard/GenomicSEM#4]
I have been trying to use genomicSEM to for my analysis, when calculating covariance matrix the error kept showing up as following:
> traits <- c("MDDvsCONT.sumstats.gz", "SCZvsCONT2.sumstats.gz")
> trait.names <- c("MDD", "SCZ")
> sample.prev <- c(0.03,0.01)
> population.prev <- sample.prev
> LDSCoutput <- ldsc(traits, sample.prev, population.prev, ld, wld, trait.names)
Read in summary statistics from MDDvsCONT.sumstats.gz 
Read in summary statistics for 1110699 SNPs 
1094275 SNPs remaining after merging the files 
Removed 0 SNPs with Chi^2 > 180 (1094275 SNPs remain) 
Results for trait MDDvsCONT.sumstats.gz 
Lambda GC: 1.2365 
Mean Chi^2: 1.2647 
Intercept: 0.9945(0.0091)
Ratio: -0.0209(0.0344)
h2: 0.0729 ( 0.0045 ) 
Error in y2$Z^2 : non-numeric argument to binary

======================================
I used the ldsc from bulik's programme to calculate genetic correlation, no such error showed up. It would be much appreciated if someone could help me with the current issue.

**Comment by MichelNivard** [comment]
Hi, 

This is likely caused by a value in the Z (or beta, or s.e.) column of the sumstat file that is not perceived as a numeric value by R (but is perceided as such or adequately ignored by LDSC which is python).

Can you check what kind of nun-numeric values could be in that column in the file?

**Comment by HongyanR** [comment]
yes, sovled! thanks!

**Comment by MichelNivard** [comment]
Great!
