### ISSUE TITLE
Error in crossprod(Delta[[g]], lavsamplestats@WLS.VD[[g]] * diff) :    non-conformable arguments

### ISSUE THREAD

**Issue by HongyanR** [MichelNivard/GenomicSEM#5]
Hi, thanks for helping me troubleshoot the last issue. I got the following error when I fit the user-specific model: 
> GWISoutput <- usermodel(LDSCoutput_all, estimation = "DWLS", model = GWISmodel1)
Error in crossprod(Delta[[g]], lavsamplestats@WLS.VD[[g]] * diff) : 
  non-conformable arguments
In addition: Warning messages:
1: In diff * diff * WLS.VD :
  longer object length is not a multiple of shorter object length
2: In lavsamplestats@WLS.VD[[g]] * diff :
  longer object length is not a multiple of shorter object length
==========================================================
I tried to extract the covariance matrix and fit it using "lavaan" package seperately. It worked with the results shown up. However, I did want to further explore the model with SNP information included, thus any help regarding the issue would be much appreciated.

**Comment by MichelNivard** [comment]
Hi,

this is hard to diagnose without seeing the model, lots of people dont want to share the full details of what they are working on publically so you can reach me at: m dot g dot nivard at vu.nl

Or reach me and Andrew via the google group: https://groups.google.com/forum/#!forum/genomic-sem-users 

Best,
Michel

**Comment by HongyanR** [comment]
Thanks, yes, it solved the issue, many apologies for delaying the response.
