### ISSUE TITLE
 Error in serialize(data, node$con) : error writing to connection 

### ISSUE THREAD

**Issue by HongyanR** [MichelNivard/GenomicSEM#6]
Hi, I am running commonfactorGWAS of 5 phenotypes using summary statistics aroun made up of 1M SNP, both commonfactorGWAS and commonfactorGWAS par won't work. with the error generating from commonfactorGWASpar shown as below:
> pfactor<-commonfactorGWASpar(SNPcov, estimation = "DWLS")
Error in serialize(data, node$con) : error writing to connection
In addition: Warning messages:
1: In split.default(Output[[1]], 1:int) :
  data length is not a multiple of split variable
2: In split.default(Output[[2]], 1:int) :
  data length is not a multiple of split variable
3: In lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats,  :
  lavaan WARNING:
    Could not compute standard errors! The information matrix could
    not be inverted. This may be a symptom that the model is not
    identified.
4: In lav_object_post_check(object) :
  lavaan WARNING: some estimated lv variances are negative
5: In lavaan::lavaan(model = Model1, sample.cov = S_Fullrun, sample.nobs = 2,  :

 Error in serialize(data, node$con) : error writing to connection .
The computer i am using for such analysis has an i9 processor, 12 cores and 32G ram.
I have been struggling with this analysis for a while. I would be most grateful if anyone could help me with this.

**Comment by MichelNivard** [comment]
THis may mean your parallel processes "died" because they ran out of memory, you ave 32GB for 11 processes (our default is Ncores-1 I think) so less then 3GB per core and you need some memory to run windows/linux. I would try:

pfactor<-commonfactorGWASpar(SNPcov, estimation = "DWLS",  cores=4)

which should limit the parallel processing to 4 cores. However you note that the non-parrallel version doesn't work either, what error do you get for commonfactorGWAS()? 

Generally I would run a GWAS for 100 or 200 test SNPs first, so that I don't have to wait for very large files to load which can make for a very frustrating programming experience.

**Comment by HongyanR** [comment]
Hi, thanks for the reply, really appreciate your response within such a
short period of time. For the commonfactorGWAS(), the error is pasted as
below:
=========================================================
> pfactor<-commonfactorGWAS(SNPcov, estimation = "DWLS")
Error in solve.default(t(S2.delt) %*% S2.W %*% S2.delt, tol = 1e-45) :
  system is computationally singular: reciprocal condition number =
1.62639e-46
In addition: Warning messages:
1: In lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats,
:
  lavaan WARNING:
    Could not compute standard errors! The information matrix could
    not be inverted. This may be a symptom that the model is not
    identified.
2: In lav_object_post_check(object) :
  lavaan WARNING: some estimated lv variances are negative
3: In lavaan::lavaan(model = Model1, sample.cov = S_Fullrun, sample.nobs =
2,  :

 Error in solve.default(t(S2.delt) %*% S2.W %*% S2.delt, tol = 1e-45) :
  system is computationally singular: reciprocal condition number =
1.62639e-46
=========================================================
For this, I googled the solution, and manually increased the tolerance
parameter for solve() function. However, same error still show up.

**Comment by HongyanR** [comment]
And set the cores as 4 won't help either, the same error showed up too:
===================================================
> pfactor<-commonfactorGWASpar(SNPcov, estimation = "DWLS", cores = 4)
Error in serialize(data, node$con) : error writing to connection
In addition: Warning messages:
1: In split.default(Output[[1]], 1:int) :
  data length is not a multiple of split variable
2: In split.default(Output[[2]], 1:int) :
  data length is not a multiple of split variable
3: In lavmodel@categorical :
  closing unused connection 23 (<-DESKTOP-8KCI772:11907)
4: In lavmodel@categorical :
  closing unused connection 22 (<-DESKTOP-8KCI772:11907)
5: In lavmodel@categorical :
  closing unused connection 21 (<-DESKTOP-8KCI772:11907)
6: In lavmodel@categorical :
  closing unused connection 20 (<-DESKTOP-8KCI772:11907)
7: In lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats,
:
  lavaan WARNING:
    Could not compute standard errors! The information matrix could
    not be inverted. This may be a symptom that the model is not
    identified.
8: In lav_object_post_check(object) :
  lavaan WARNING: some estimated lv variances are negative
9: In lavaan::lavaan(model = Model1, sample.cov = S_Fullrun, sample.nobs =
2,  :

 Error in serialize(data, node$con) : error writing to connection
======================================================

**Comment by MichelNivard** [comment]
can you share the matrix in S (covariance matrix) of  the ldsc object you made earlier? Feel free to strip the variable names if you don't want to share what your working on precisely with the entire internet. Perhaps the error you have with commonfactorGWAS() is data related.


 The parrallel issue may still be memory related, 1 million SNPs is a large chunk to run at once. Try if that error persists with 100 SNPs. 

It will help me debug if you could share the entire script.

**Comment by HongyanR** [comment]
Share the S matrix with you: 
https://www.dropbox.com/sh/xhzci63teslrc3g/AAAIvcaRzL9zXy6uomGZjO9Qa?dl=0

**Comment by MichelNivard** [comment]
Download doesn't seem to work...

**Comment by HongyanR** [comment]
Hi Many apologies! the file is too big for to upload to Dropbox, I am trying google drive now and will update the link when the uploading succeed.
 BTW, I found there probably is something wrong with function sumstats(), mine data is made up of 7 continuous traits, their effect size is beta and se from OLS. Would you further clarify how I should set the parameters for sumstast(), especially for "se.logit, OLS=NULL,linprob=NULL,prop=NULL,N=NULL" ?

**Comment by MichelNivard** [comment]
se.logit=c(F,F,F,F,F,F,F), OLS = c(T,T,T,T,T,T,T),  linprob=NULL,prop=NULLand N is a vector of N per trait. Perhaps send me a file with only 1 SNP in it? because things have to be REALLY big to be too big for diopbox

**Comment by MichelNivard** [comment]
I emaield you up[on receiving your data. Looks to be a data issue, lets continue the conversation via email.

**Comment by MichelNivard** [comment]
Closing this now, we'll resolve via email

**Comment by lilianpatricia** [comment]
Hello! 

Did anyone manage to find a solution for the error?
_Error in serialize(data, node$con) : error writing to connection_

I am working in R with a very large dataset, so I suppose it is something related to memory. 

Manually increasing the memory with the function _memory.limit()_ and/or reducing the number of cores used in parallel processing does **not** work either.

Thanks!

**Comment by lilianpatricia** [comment]
Hello MichelNivard, thank you for your answer.

I am sorry but I do not know how to execute your suggestion (_to restrict the input to ~100 SNPs_).

Can you please tell me how should I do it?

Thanks!
