### ISSUE TITLE
Error in icount(int) : could not find function "icount"

### ISSUE THREAD

**Issue by jprnz** [MichelNivard/GenomicSEM#8]
When running the commonfactorGWAS command I received the error above.

I am pretty sure this is due to not loading the `iterators` package and could be alleviated by including this package in your `NAMESPACE` file. I can manually load the library and the error goes away.

Thank you!

**Comment by MichelNivard** [comment]
Fixed, sorry about that.

**Comment by jprnz** [comment]
Thanks!
