### ISSUE TITLE
 addSNPs not executable on R in windows OS

### ISSUE THREAD

**Issue by HongyanR** [MichelNivard/GenomicSEM#9]
SNPcov<-addSNPs(LDSCoutput, p_sumstats,SNPSE = FALSE,parallel=TRUE, cores = NULL)
[1] "Creating Sampling Covariance [V] matrices"
Error in mclapply(X = 1:f, FUN = function(X) { : 
  'mc.cores' > 1 is not supported on Windows

**Comment by MichelNivard** [comment]
Hi,

Yes unfortunately no parallel analyses in Windows. This is not a GenomicSEM specific issue. You can set parallel=TRUE and cores = 1.

Best,
Michel

**Comment by MichelNivard** [comment]
Sorry I made an error in my comment, I update it now
